package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/snowmerak/socketgen/parser"
)

const csharpTemplate = `// Code generated by socketgen. DO NOT EDIT.
using Google.Protobuf;
using {{.PackageName | toPascalCase}};

public interface IPacketHandler {
{{- range .Payloads }}
    void On{{.Name}}(Header header, {{.Name}} msg);
{{- end }}
}

public static class PacketDispatcher {
    public static void Dispatch(byte[] data, IPacketHandler handler) {
        var pkt = GamePacket.Parser.ParseFrom(data);
        
        switch (pkt.PayloadCase) {
{{- range .Payloads }}
            case GamePacket.PayloadOneofCase.{{.Name}}:
                handler.On{{.Name}}(pkt.Header, pkt.{{.Name}});
                break;
{{- end }}
        }
    }
}
`

func GenerateCSharp(result *parser.ParseResult, outDir string) error {
	funcMap := template.FuncMap{
		"toPascalCase": toPascalCase,
	}

	tmpl, err := template.New("csharp").Funcs(funcMap).Parse(csharpTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse csharp template: %w", err)
	}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	outFile := filepath.Join(outDir, "PacketDispatcher.cs")
	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, result)
}
