package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/snowmerak/socketgen/parser"
)

const dartTemplate = `// Code generated by socketgen. DO NOT EDIT.
import 'packet.pb.dart';

abstract class PacketHandler {
{{- range .Payloads }}
  void on{{.Name}}(Header header, {{.Name}} msg);
{{- end }}
}

void dispatch(List<int> data, PacketHandler handler) {
  final pkt = GamePacket.fromBuffer(data);
  
  switch (pkt.whichPayload()) {
{{- range .Payloads }}
    case GamePacket_Payload.{{.FieldName | toCamelCase}}:
      handler.on{{.Name}}(pkt.header, pkt.{{.FieldName | toCamelCase}});
      break;
{{- end }}
    case GamePacket_Payload.notSet:
      break;
  }
}
`

func GenerateDart(result *parser.ParseResult, outDir string) error {
	funcMap := template.FuncMap{
		"toCamelCase": toCamelCase,
	}

	tmpl, err := template.New("dart").Funcs(funcMap).Parse(dartTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse dart template: %w", err)
	}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	outFile := filepath.Join(outDir, "packet_dispatcher.dart")
	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, result)
}
