package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/snowmerak/socketgen/parser"
)

const javaTemplate = `// Code generated by socketgen. DO NOT EDIT.
package {{.PackageName}};

import {{.PackageName}}.GamePacket;
import {{.PackageName}}.Header;
{{- range .Payloads }}
import {{$.PackageName}}.{{.Name}};
{{- end }}
import com.google.protobuf.InvalidProtocolBufferException;

public interface PacketHandler {
{{- range .Payloads }}
    void on{{.Name}}(Header header, {{.Name}} msg);
{{- end }}
}

class PacketDispatcher {
    public static void dispatch(byte[] data, PacketHandler handler) throws InvalidProtocolBufferException {
        GamePacket pkt = GamePacket.parseFrom(data);
        
        switch (pkt.getPayloadCase()) {
{{- range .Payloads }}
            case {{.FieldName | toUpper}}:
                handler.on{{.Name}}(pkt.getHeader(), pkt.get{{.Name}}());
                break;
{{- end }}
            case PAYLOAD_NOT_SET:
                break;
        }
    }
}
`

func GenerateJava(result *parser.ParseResult, outDir string) error {
	funcMap := template.FuncMap{
		"toUpper": strings.ToUpper,
	}

	tmpl, err := template.New("java").Funcs(funcMap).Parse(javaTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse java template: %w", err)
	}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	outFile := filepath.Join(outDir, "PacketDispatcher.java")
	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, result)
}
