package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/snowmerak/socketgen/parser"
)

const kotlinTemplate = `// Code generated by socketgen. DO NOT EDIT.
package {{.PackageName}}

import {{.PackageName}}.GamePacket
import {{.PackageName}}.Header
{{- range .Payloads }}
import {{$.PackageName}}.{{.Name}}
{{- end }}

interface PacketHandler {
{{- range .Payloads }}
    fun on{{.Name}}(header: Header, msg: {{.Name}})
{{- end }}
}

object PacketDispatcher {
    fun dispatch(data: ByteArray, handler: PacketHandler) {
        val pkt = GamePacket.parseFrom(data)
        
        when (pkt.payloadCase) {
{{- range .Payloads }}
            GamePacket.PayloadCase.{{.FieldName | toUpper}} -> handler.on{{.Name}}(pkt.header, pkt.{{.FieldName | toCamelCase}})
{{- end }}
            GamePacket.PayloadCase.PAYLOAD_NOT_SET -> {} // Handle not set case
            else -> {} // Handle unknown case
        }
    }
}
`

func GenerateKotlin(result *parser.ParseResult, outDir string) error {
	funcMap := template.FuncMap{
		"toCamelCase": toCamelCase,
		"toUpper":     strings.ToUpper,
	}

	tmpl, err := template.New("kotlin").Funcs(funcMap).Parse(kotlinTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse kotlin template: %w", err)
	}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	outFile := filepath.Join(outDir, "PacketDispatcher.kt")
	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, result)
}
