package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/snowmerak/socketgen/parser"
)

const phpTemplate = `<?php
// Code generated by socketgen. DO NOT EDIT.
namespace {{.PackageName | toPascalCase}};

use {{.PackageName | toPascalCase}}\GamePacket;
use {{.PackageName | toPascalCase}}\Header;
{{- range .Payloads }}
use {{$.PackageName | toPascalCase}}\{{.Name}};
{{- end }}

interface PacketHandler {
{{- range .Payloads }}
    public function on{{.Name}}(Header $header, {{.Name}} $msg);
{{- end }}
}

class PacketDispatcher {
    public static function dispatch($data, PacketHandler $handler) {
        $pkt = new GamePacket();
        $pkt->mergeFromString($data);

        switch ($pkt->getPayload()) {
{{- range .Payloads }}
            case '{{.FieldName}}':
                $handler->on{{.Name}}($pkt->getHeader(), $pkt->get{{.Name}}());
                break;
{{- end }}
        }
    }
}
`

func GeneratePHP(result *parser.ParseResult, outDir string) error {
	funcMap := template.FuncMap{
		"toPascalCase": toPascalCase, // Reusing from csharp_gen.go if in same package, otherwise need to duplicate or move to util
	}

	tmpl, err := template.New("php").Funcs(funcMap).Parse(phpTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse php template: %w", err)
	}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	outFile := filepath.Join(outDir, "PacketDispatcher.php")
	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, result)
}
