package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/snowmerak/socketgen/parser"
)

const pyTemplate = `# Code generated by socketgen. DO NOT EDIT.
from abc import ABC, abstractmethod
from .packet_pb2 import GamePacket

class PacketHandler(ABC):
{{- range .Payloads }}
    @abstractmethod
    def on_{{.FieldName}}(self, header, msg):
        pass
{{- end }}

def dispatch(data: bytes, handler: PacketHandler):
    pkt = GamePacket()
    pkt.ParseFromString(data)
    
    type_str = pkt.WhichOneof('payload')
    
{{- range $i, $p := .Payloads }}
    {{if eq $i 0}}if{{else}}elif{{end}} type_str == '{{.FieldName}}':
        handler.on_{{.FieldName}}(pkt.header, pkt.{{.FieldName}})
{{- end }}
`

func GeneratePython(result *parser.ParseResult, outDir string) error {
	tmpl, err := template.New("python").Parse(pyTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse python template: %w", err)
	}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	outFile := filepath.Join(outDir, "packet_dispatcher.py")
	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, result)
}
