package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/snowmerak/socketgen/parser"
)

const rubyTemplate = `# Code generated by socketgen. DO NOT EDIT.
require 'packet_pb'

module PacketDispatcher
  def self.dispatch(data, handler)
    pkt = {{.PackageName | toPascalCase}}::GamePacket.decode(data)
    
    case pkt.payload
{{- range .Payloads }}
    when :{{.FieldName}}
      handler.on_{{.FieldName}}(pkt.header, pkt.{{.FieldName}})
{{- end }}
    end
  end
end
`

func GenerateRuby(result *parser.ParseResult, outDir string) error {
	funcMap := template.FuncMap{
		"toPascalCase": toPascalCase,
	}

	tmpl, err := template.New("ruby").Funcs(funcMap).Parse(rubyTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse ruby template: %w", err)
	}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	outFile := filepath.Join(outDir, "packet_dispatcher.rb")
	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, result)
}
