package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/snowmerak/socketgen/parser"
)

const rubyTemplate = `# Code generated by socketgen. DO NOT EDIT.
require 'packet_pb'

module PacketDispatcher
  def self.dispatch(data, handler)
    pkt = {{.PackageName | toPascalCase}}::GamePacket.decode(data)
    
    case pkt.payload
{{- range .Payloads }}
    when :{{.FieldName}}
      handler.on_{{.FieldName}}(pkt.header, pkt.{{.FieldName}})
{{- end }}
    end
  end

  def self.serve(stream, handler)
    loop do
      begin
        data = stream.read_packet
        dispatch(data, handler)
      rescue => e
        puts "Dispatch error: #{e.message}"
      end
    end
  end

{{- range .Payloads }}

  def self.send_{{.FieldName}}(stream, header, msg)
    pkt = {{$.PackageName | toPascalCase}}::GamePacket.new(
      header: header,
      {{.FieldName}}: msg
    )
    stream.write_packet({{$.PackageName | toPascalCase}}::GamePacket.encode(pkt))
  end
{{- end }}
end

# Interface documentation for PacketStream
# class PacketStream
#   def read_packet; end
#   def write_packet(data); end
# end

# Interface documentation for PacketHandler
# class PacketHandler
{{- range .Payloads }}
#   def on_{{.FieldName}}(header, msg); end
{{- end }}
# end
`

func GenerateRuby(result *parser.ParseResult, outDir string) error {
	funcMap := template.FuncMap{
		"toPascalCase": toPascalCase,
	}

	tmpl, err := template.New("ruby").Funcs(funcMap).Parse(rubyTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse ruby template: %w", err)
	}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	outFile := filepath.Join(outDir, "packet_dispatcher.rb")
	f, err := os.Create(outFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer f.Close()

	return tmpl.Execute(f, result)
}
